source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'SwiftProjectDemo' do

#swift
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'SnapKit'
    pod 'HandyJSON'
    pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'

end





