source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'SwiftProjectDemo' do
    
#swift常用库

#网络请求
#pod 'Moya', '~> 11.0'
pod 'Moya/RxSwift', '~> 11.0'
pod 'Alamofire'

#Json解析库
pod 'HandyJSON', '~> 4.0.0-beta.1'

#自动布局
pod 'SnapKit'

#ReactiveCocoa框架Swift版本（响应链编程框架）
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'

# MJRefresh的Swift替代
pod 'GTMRefresh'

#Banner轮播控件
pod 'LLCycleScrollView'

#Swift时间处理
pod 'SwiftDate'

end





