source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'SwiftProjectDemo' do
#swift
#pod 'Moya', '~> 11.0'
pod 'Moya/RxSwift', '~> 11.0'
pod 'SnapKit'
pod 'HandyJSON', '~> 4.0.0-beta.1'
pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'

end





