source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'OCProjectDemo' do
    pod 'Masonry', '~> 1.0.2'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'ReactiveObjC'
    pod 'CLNetworking'
end

